server:
  port: 8090
  undertow:
    # 设置IO线程数, 它主要执行非阻塞的任务,它们会负责多个连接, 默认设置每个CPU核心一个线程
    io-threads: 16
    # 阻塞任务线程池, 当执行类似servlet请求阻塞操作, undertow会从这个线程池中取得线程,它的值设置取决于系统的负载
    worker-threads: 128
    # 以下的配置会影响buffer,这些buffer会用于服务器连接的IO操作,有点类似netty的池化内存管理
    # 每块buffer的空间大小,越小的空间被利用越充分
    buffer-size: 32
    # 是否分配的直接内存
    direct-buffers: true
spring:
  datasource:
    #name : druidDataSource
    type : com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/royeflow?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
      username: roye
      password: 123456
      filters: stat,wall,log4j,config  #配置监控统计拦截的filters,去掉后监控界面sql无法进行统计，wall用于防火墙
      max-active: 100  #最大连接数
      initial-size: 5  #初始化大小
      max-wait: 60000  #获取连接等待超时时间
      min-idle: 1      #最小连接数
      time-between-eviction-runs-millis: 60000  #间隔多久才进行一次检测，检查需要关闭的空闲连接，单位是毫秒
      min-evictable-idle-time-millis: 300000    #一个连接在池中最小生存的时间，单位是毫秒
      validation-query: select 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 50
      max-pool-prepared-statement-per-connection-size: 20
      # WebStatFilter配置，说明请参考Druid Wiki，配置_配置WebStatFilter
      # 是否启用StatFilter默认值true
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
        session-stat-enable: false
        session-stat-max-count: 1000
        principal-cookie-name: admin
        principal-session-name: admin
        profile-enable: true
      stat-view-servlet:
        url-pattern: /druid/*  # 监控页面访问路径
        # 允许清空统计数据
        reset-enable: true
        login-username: roye
        login-password: 123456
        # StatViewSerlvet展示出来的监控信息比较敏感，是系统运行的内部情况，如果你需要做访问控制，可以配置allow和deny这两个参数
        # deny优先于allow，如果在deny列表中，就算在allow列表中，也会被拒绝。如果allow没有配置或者为空，则允许所有访问
        # 配置的格式
          # <IP>
          # 或者<IP>/<SUB_NET_MASK_size>其中128.242.127.1/24
          # 24表示，前面24位是子网掩码，比对的时候，前面24位相同就匹配,不支持IPV6。
        allow:
        deny:
  boot:  #系统服务监控
    admin:
      client:
        url: "http://127.0.0.1:8100"
  #zipkin
  zipkin:
    base-url: http://127.0.0.1:9411
  sleuth:
    sampler:
      probability: 1  #样本采集量，默认为0.1
  thymeleaf:
    cache: false
  devtools:
    restart:
      enabled: true
  #rabbitmq:
  #  host: 127.0.0.1
  #  port: 5672
  #  username: guest
  #  password: guest
  main:
    allow-bean-definition-overriding: true #当遇到相同名字的时候，是否允许覆盖
  profiles:
    active: dev
    main:
      allow-bean-definition-overriding: true #当遇到相同名字的时候，是否允许覆盖
  # jsp配置
  mvc:
    static-path-pattern: /**
    # 默认值为 classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/
    view: 
      prefix: /WEB-INF/roadflow_views/
      suffix: .jsp
  redis:
    # redis数据库索引（默认为0），我们使用索引为3的数据库，避免和其他数据库冲突
    database: 3
    # redis服务器地址（默认为localhost）
    host: 127.0.0.1
    # redis端口（默认为6379）
    port: 6379
    # redis访问密码（默认为空）
    password: 123456
    # redis连接超时时间（单位为毫秒）
    timeout: 20000
    # redis连接池配置
    jedis:
      pool:
        # 最大可用连接数（默认为8，负数表示无限）
        max-active: 8
        # 最大空闲连接数（默认为8，负数表示无限）
        max-idle: 8
        # 最小空闲连接数（默认为0，该值只有为正数才有作用）
        min-idle: 0
        # 从连接池中获取连接最大等待时间（默认为-1，单位为毫秒，负数表示无限）
        max-wait: -1
  session:
    store-type: redis   #设置session保存为默认redis的方式
    
  #security:
   # user:
   #   name: roye
   #   password: 123456

#开放健康检查接口        
management: 
  endpoints:
    web:
      exposure:
        include: "*"  #监控开放接口“*”代表全部
  
    
#断熔器
feign:
  hystrix:
    enabled: true
    
MyBatis:
  type-aliases-package: cn.roye.flow
  mapper-locations: classpath:mapping_mysql/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  
turbine:
  instanceUrlSuffix: /hystrix.stream  #没有的话会出现异常

